version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: minibank-postgres
    environment:
      POSTGRES_DB: minibank
      POSTGRES_USER: minibank
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minibank"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: minibank-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/minibank
      SPRING_DATASOURCE_USERNAME: minibank
      SPRING_DATASOURCE_PASSWORD: 123456
    restart: unless-stopped

volumes:
  postgres_data:
